version: '3'

services:
  # https://hub.docker.com/_/php/
  task-manager-php:
    container_name: task-manager-php
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    expose:
      - 9000
    depends_on:
      - task-manager-db
    volumes:
      - .:/var/www/html

  # https://hub.docker.com/_/nginx/
  task-manager-nginx:
    container_name: task-manager-nginx
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - task-manager-php

###> doctrine/doctrine-bundle ###
  task-manager-db:
    container_name: task-manager-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
#      - "5432:5432"
      - "127.0.0.1:5432:5432"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
