version: '3'

services:
###> doctrine/doctrine-bundle ###
  task-manager-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
